"""ilk sema

Revision ID: 50b7106adecd
Revises: 
Create Date: 2026-08-08 14:28:50.989866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import awe.persistence.types


# revision identifiers, used by Alembic.
revision: str = '50b7106adecd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('received_at', awe.persistence.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'event_id', name='uq_events_project_event')
    )
    op.create_table('families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_key', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('representative_variants', sa.JSON(), nullable=False),
    sa.Column('relationships', sa.JSON(), nullable=False),
    sa.Column('cohesion', sa.Float(), nullable=False),
    sa.Column('created_at', awe.persistence.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', awe.persistence.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_key')
    )
    op.create_index('ix_families_subject_scope', 'families', ['project_id', 'subject_id'], unique=False)
    op.create_table('habit_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', awe.persistence.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id')
    )
    op.create_table('plan_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_key', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=16), nullable=False),
    sa.Column('anchor', sa.JSON(), nullable=False),
    sa.Column('bindings', sa.JSON(), nullable=False),
    sa.Column('target_binding', sa.JSON(), nullable=True),
    sa.Column('supporting_occurrences', sa.Integer(), nullable=False),
    sa.Column('risk_decision', sa.String(length=32), nullable=False),
    sa.Column('risk_reason_codes', sa.JSON(), nullable=False),
    sa.Column('risk_evidence', sa.JSON(), nullable=False),
    sa.Column('reduced_bindings', sa.JSON(), nullable=False),
    sa.Column('benefit_median', sa.Float(), nullable=False),
    sa.Column('benefit_p25', sa.Float(), nullable=False),
    sa.Column('benefit_p75', sa.Float(), nullable=False),
    sa.Column('benefit_coverage', sa.Float(), nullable=False),
    sa.Column('benefit_sample_size', sa.Integer(), nullable=False),
    sa.Column('benefit_meets_minimum', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', awe.persistence.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_key')
    )
    op.create_index('ix_plan_candidates_family', 'plan_candidates', ['family_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_key', sa.String(length=256), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('started_at', awe.persistence.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', awe.persistence.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ordering_confidence', sa.String(length=16), nullable=False),
    sa.Column('ended_by_breaks_episode', sa.Boolean(), nullable=False),
    sa.Column('entry_trigger', sa.String(length=32), nullable=False),
    sa.Column('entry_screen', sa.String(length=256), nullable=True),
    sa.Column('has_shortcut_trigger', sa.Boolean(), nullable=False),
    sa.Column('final_status', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('ambiguous_family_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_key')
    )
    op.create_index('ix_series_subject_scope', 'series', ['project_id', 'subject_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', awe.persistence.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('effect', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('screen', sa.String(length=256), nullable=True),
    sa.Column('widget', sa.String(length=256), nullable=True),
    sa.Column('target', sa.String(length=256), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('breaks_episode', sa.Boolean(), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('mapping_version', sa.String(length=64), nullable=False),
    sa.Column('quality_has_screen', sa.Boolean(), nullable=False),
    sa.Column('quality_has_widget', sa.Boolean(), nullable=False),
    sa.Column('quality_has_session_id', sa.Boolean(), nullable=False),
    sa.Column('quality_is_synthetic_session', sa.Boolean(), nullable=False),
    sa.Column('quality_mapping_warnings', sa.JSON(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'event_id', name='uq_observations_project_event')
    )
    op.create_index('ix_observations_series', 'observations', ['series_id'], unique=False)
    op.create_index('ix_observations_subject_scope', 'observations', ['project_id', 'subject_id', 'session_id'], unique=False)
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suggestion_key', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('primary_plan_id', sa.Integer(), nullable=False),
    sa.Column('fallback_plan_ids', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('created_at', awe.persistence.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', awe.persistence.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('dismissed_at', awe.persistence.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('dismiss_cooldown_until', awe.persistence.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['primary_plan_id'], ['plan_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id'),
    sa.UniqueConstraint('suggestion_key')
    )
    op.create_index('ix_suggestions_subject_scope', 'suggestions', ['project_id', 'subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_suggestions_subject_scope', table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index('ix_observations_subject_scope', table_name='observations')
    op.drop_index('ix_observations_series', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_series_subject_scope', table_name='series')
    op.drop_table('series')
    op.drop_index('ix_plan_candidates_family', table_name='plan_candidates')
    op.drop_table('plan_candidates')
    op.drop_table('habit_evaluations')
    op.drop_index('ix_families_subject_scope', table_name='families')
    op.drop_table('families')
    op.drop_table('events')
    # ### end Alembic commands ###
